WEB/src/Entity/Calendar.php
<?php

namespace App\Entity;

use App\Repository\CalendarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CalendarRepository::class)
 */
class Calendar
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Ajouter un titre")
     */
    private $Titre;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="Ajouter un date de debut")
     */
    private $start;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="Ajouter un date de fin")
     */
    private $end;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     */
    private $allday;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $background_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $boarder_color;

    /**
     * @ORM\Column(type="string", length=7)
     */
    private $texte_color;

    /**
     * @ORM\ManyToMany(targetEntity=EventsReservation::class, mappedBy="LesEvenements")
     */
    private $eventsReservations;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="calendars")
     */
    private $User;

    public function __construct()
    {
        $this->eventsReservations = new ArrayCollection();
    }





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): self
    {
        $this->start = $start;

        return $this;
    }

    public function getEnd(): ?\DateTimeInterface
    {
        return $this->end;
    }

    public function setEnd(\DateTimeInterface $end): self
    {
        $this->end = $end;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAllday(): ?bool
    {
        return $this->allday;
    }

    public function setAllday(bool $allday): self
    {
        $this->allday = $allday;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->background_color;
    }

    public function setBackgroundColor(string $background_color): self
    {
        $this->background_color = $background_color;

        return $this;
    }

    public function getBoarderColor(): ?string
    {
        return $this->boarder_color;
    }

    public function setBoarderColor(string $boarder_color): self
    {
        $this->boarder_color = $boarder_color;

        return $this;
    }

    public function getTexteColor(): ?string
    {
        return $this->texte_color;
    }

    public function setTexteColor(string $texte_color): self
    {
        $this->texte_color = $texte_color;

        return $this;
    }



    public function __toString() {
        return $this->Titre;
    }

    /**
     * @return Collection<int, EventsReservation>
     */
    public function getEventsReservations(): Collection
    {
        return $this->eventsReservations;
    }

    public function addEventsReservation(EventsReservation $eventsReservation): self
    {
        if (!$this->eventsReservations->contains($eventsReservation)) {
            $this->eventsReservations[] = $eventsReservation;
            $eventsReservation->addLesEvenement($this);
        }

        return $this;
    }

    public function removeEventsReservation(EventsReservation $eventsReservation): self
    {
        if ($this->eventsReservations->removeElement($eventsReservation)) {
            $eventsReservation->removeLesEvenement($this);
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }



}

WEB/src/Form/CalendarType.php
<?php

namespace App\Form;

use App\Entity\Calendar;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CalendarType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Titre')
            ->add('start', DateTimeType::class, [
                'date_widget' => 'single_text'
            ])
            ->add('end', DateTimeType::class, [
                'date_widget' => 'single_text'
            ])
            ->add('description')
            ->add('allday')
            ->add('background_color', ColorType::class)
            ->add('boarder_color', ColorType::class)
            ->add('texte_color', ColorType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Calendar::class,
        ]);
    }
}

WEB/src/Controller/CalendarController.php
<?php

namespace App\Controller;

use App\Entity\Calendar;
use App\Form\CalendarType;
use App\Repository\CalendarRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/calendar")
 */
class CalendarController extends AbstractController
{
    /**
     * @Route("/", name="calendar_index", methods={"GET"})
     */
    public function index(Request $request,CalendarRepository $calendarRepository,PaginatorInterface $paginator): Response
    { $donnees = $this->getDoctrine()->getRepository(Calendar::class)->findBy([],['id' => 'desc']);

        $calendarRepository = $paginator->paginate(
            $donnees,
            $request->query->getInt('page', 1),
            1
        );
        return $this->render('calendar/index.html.twig', [
            'calendars' => $calendarRepository,
        ]);
    }

    /**
     * @Route("/new", name="calendar_new", methods={"GET", "POST"})
     */
    public function new(UserRepository $usrRep ,Request $request, EntityManagerInterface $entityManager): Response
    {
        $calendar = new Calendar();
        $form = $this->createForm(CalendarType::class, $calendar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user=$this->getUser()->getUsername();
            $currentuser=$usrRep->findOneBy(array('Username'=>$user));
            $calendar->setUser($currentuser);
            $entityManager->persist($calendar);
            $entityManager->flush();

            return $this->redirectToRoute('calendar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('calendar/new.html.twig', [
            'calendar' => $calendar,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="calendar_show", methods={"GET"})
     */
    public function show(Calendar $calendar): Response
    {
        return $this->render('calendar/show.html.twig', [
            'calendar' => $calendar,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="calendar_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Calendar $calendar, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CalendarType::class, $calendar);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('calendar_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('calendar/edit.html.twig', [
            'calendar' => $calendar,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="calendar_delete", methods={"POST"})
     */
    public function delete(Request $request, Calendar $calendar, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$calendar->getId(), $request->request->get('_token'))) {
            $entityManager->remove($calendar);
            $entityManager->flush();
        }

        return $this->redirectToRoute('calendar_index', [], Response::HTTP_SEE_OTHER);
    }
    public function deletebydate(Request $request, Calendar $calendar, EntityManagerInterface $entityManager){
        $Today = getdate();
        if (!Today >= getEnd()){
            $entityManager->remove($calendar);
            $entityManager->flush();
        }
    }

}

WEB/templates/calendar/_delete_form.html.twig
<form method="post" action="{{ path('calendar_delete', {'id': calendar.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ calendar.id) }}">
    <button class="btn">Delete</button>
</form>

WEB/templates/calendar/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

WEB/templates/calendar/edit.html.twig
{% extends "base_BACK.html.twig" %}

{% block back_content %}
{% block title %}Edit Calendar{% endblock %}

{% block body %}
    <h1>Edit Calendar</h1>

    {{ include('calendar/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('calendar_index') }}">back to list</a>

    {{ include('calendar/_delete_form.html.twig') }}
{% endblock %}
{% endblock %}
{% block back_footer %}
{% endblock %}

WEB/templates/calendar/index.html.twig
{% extends "base_BACK.html.twig" %}

{% block back_content %}
{% block title %}La Listes Des Evenements{% endblock %}

{% block body %}
    <h1>Events List</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Formateur</th>
                <th>Start</th>
                <th>End</th>
                <th>Description</th>
                <th>Allday</th>
                <th>Background_color</th>
                <th>Boarder_color</th>
                <th>Texte_color</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for calendar in calendars %}
            <tr>
                <td>{{ calendar.id }}</td>
                <td>{{ calendar.Titre }}</td>
                <td>{{ calendar.User }}   </td>
                <td>{{ calendar.start ? calendar.start|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ calendar.description }}</td>
                <td>{{ calendar.allday ? 'Yes' : 'No' }}</td>
                <td>{{ calendar.backgroundColor }}</td>
                <td>{{ calendar.boarderColor }}</td>
                <td>{{ calendar.texteColor }}</td>
                <td>
                    <a href="{{ path('calendar_show', {'id': calendar.id}) }}">show</a>
                    <a href="{{ path('calendar_edit', {'id': calendar.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('calendar_new') }}">Create new</a>
    <div>{{ knp_pagination_render(calendars) }}</div>

{% endblock %}
{% endblock %}
{% block back_footer %}
{% endblock %}

WEB/templates/calendar/new.html.twig
{% extends "base_BACK.html.twig" %}

{% block back_content %}

{% block title %}New Calendar{% endblock %}

{% block body %}
    <h1>Create new Calendar</h1>

    {{ include('calendar/_form.html.twig') }}

    <a href="{{ path('calendar_index') }}">back to list</a>
{% endblock %}
{% endblock %}
{% block back_footer %}
{% endblock %}

WEB/templates/calendar/show.html.twig
{% extends "base_BACK.html.twig" %}

{% block back_content %}

{% block title %}Calendar{% endblock %}

{% block body %}
    <h1>Calendar</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ calendar.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ calendar.Titre }}</td>
            </tr>
            <tr>
                <th>Start</th>
                <td>{{ calendar.start ? calendar.start|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ calendar.end ? calendar.end|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ calendar.description }}</td>
            </tr>
            <tr>
                <th>Allday</th>
                <td>{{ calendar.allday ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Background_color</th>
                <td>{{ calendar.backgroundColor }}</td>
            </tr>
            <tr>
                <th>Boarder_color</th>
                <td>{{ calendar.boarderColor }}</td>
            </tr>
            <tr>
                <th>Texte_color</th>
                <td>{{ calendar.texteColor }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('calendar_index') }}">back to list</a>

    <a href="{{ path('calendar_edit', {'id': calendar.id}) }}">edit</a>

    {{ include('calendar/_delete_form.html.twig') }}
{% endblock %}
{% endblock %}
{% block back_footer %}
{% endblock %}